parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    experimentalObjectRestSpread: true
env:
  node : true
  es6: true
extends: 'eslint:recommended'
rules:
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-console: off
  prefer-spread: error
